name: Node.js CI

on: [push]

jobs:
  tests:
    env:
      SCOPE_DSN: ${{ secrets.SCOPE_DSN }}
      CI: true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm test
